# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='logo',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
