# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0003_auto_20170123_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
