# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:42
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0004_contact_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='jingle',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
