# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:44
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0005_contact_jingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
